<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>RealEstatesWatcher.UI.Console</RootNamespace>
    <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.6.3</Version>
    <AssemblyVersion>1.6.3.0</AssemblyVersion>
    <Authors>Martin Vrábel</Authors>
    <Product>Real Estates Watcher</Product>
    <Description>Simple C# script for periodic watching of selected Real estate advertisement portals with notifications on new ads.</Description>
    <PackageProjectUrl>https://github.com/supermartzin/real-estates-watcher</PackageProjectUrl>
    <RepositoryUrl>https://github.com/supermartzin/real-estates-watcher</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>GPL-3.0</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Diagnostics.Common" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Ini" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="NLog.Extensions.Logging" />
    <PackageReference Include="Sentry.Extensions.Logging" />
    <PackageReference Include="Sentry.Profiling" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Filters\RealEstatesWatcher.AdPostsFilters.BasicFilter\RealEstatesWatcher.AdPostsFilters.BasicFilter.csproj" />
    <ProjectReference Include="..\Handlers\RealEstatesWatcher.AdPostsHandlers.Email\RealEstatesWatcher.AdPostsHandlers.Email.csproj" />
    <ProjectReference Include="..\Handlers\RealEstatesWatcher.AdPostsHandlers.File\RealEstatesWatcher.AdPostsHandlers.File.csproj" />
    <ProjectReference Include="..\Handlers\RealEstatesWatcher.AdPostsHandlers.Telegram\RealEstatesWatcher.AdPostsHandlers.Telegram.csproj" />
    <ProjectReference Include="..\Portals\RealEstatesWatcher.AdsPortals.BazosCz\RealEstatesWatcher.AdsPortals.BazosCz.csproj" />
    <ProjectReference Include="..\Portals\RealEstatesWatcher.AdsPortals.BidliCz\RealEstatesWatcher.AdsPortals.BidliCz.csproj" />
    <ProjectReference Include="..\Portals\RealEstatesWatcher.AdsPortals.BravisCz\RealEstatesWatcher.AdsPortals.BravisCz.csproj" />
    <ProjectReference Include="..\Portals\RealEstatesWatcher.AdsPortals.CeskeRealityCz\RealEstatesWatcher.AdsPortals.CeskeRealityCz.csproj" />
    <ProjectReference Include="..\Portals\RealEstatesWatcher.AdsPortals.FlatZoneCz\RealEstatesWatcher.AdsPortals.FlatZoneCz.csproj" />
    <ProjectReference Include="..\Portals\RealEstatesWatcher.AdsPortals.MMRealityCz\RealEstatesWatcher.AdsPortals.MMRealityCz.csproj" />
    <ProjectReference Include="..\Portals\RealEstatesWatcher.AdsPortals.RealcityCz\RealEstatesWatcher.AdsPortals.RealcityCz.csproj" />
    <ProjectReference Include="..\Portals\RealEstatesWatcher.AdsPortals.RealityIdnesCz\RealEstatesWatcher.AdsPortals.RealityIdnesCz.csproj" />
    <ProjectReference Include="..\Portals\RealEstatesWatcher.AdsPortals.RemaxCz\RealEstatesWatcher.AdsPortals.RemaxCz.csproj" />
    <ProjectReference Include="..\Portals\RealEstatesWatcher.AdsPortals.SrealityCz\RealEstatesWatcher.AdsPortals.SrealityCz.csproj" />
    <ProjectReference Include="..\Portals\RealEstatesWatcher.AdsPortals.BezrealitkyCz\RealEstatesWatcher.AdsPortals.BezrealitkyCz.csproj" />
    <ProjectReference Include="..\RealEstatesWatcher.Core\RealEstatesWatcher.Core.csproj" />
    <ProjectReference Include="..\Scrapers\RealEstatesWatcher.Scrapers\RealEstatesWatcher.Scrapers.csproj" />
    <ProjectReference Include="..\Tools\RealEstatesWatcher.Tools.Attributes\RealEstatesWatcher.Tools.Attributes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config-templates\engine.ini">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="config-templates\portals.ini">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="configs\engine.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="config-templates\filters.ini">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="configs\filters.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="configs\handlers.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="config-templates\handlers.ini">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="configs\portals.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="configs\scraper.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="configs\portals-old.ini">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
